[package]
name = "nam-wasm-instrument"
version = "0.5.3-terp.2"
edition = "2021"
rust-version = "1.56.1"
authors = ["Parity Technologies <admin@parity.io>"]
license = "MIT OR Apache-2.0"
description = "(Terp fork) Instrument and transform wasm modules."
keywords = ["wasm", "webassembly", "blockchain", "gas-metering", "parity"]
categories = ["wasm", "no-std"]
repository = "https://github.com/permissionlessweb/nam-wasm-instrument"
include = ["src/**/*", "LICENSE-*", "README.md"]

[[bench]]
name = "instrumentation"
harness = false
path = "benches/instrumentation.rs"

[[bench]]
name = "execution"
harness = false
path = "benches/execution.rs"

[profile.bench]
lto = "fat"
codegen-units = 1

[dependencies]
parity-wasm = { path = "vendor/parity-wasm", default-features = false, package = "parity-wasm" }

[dev-dependencies]
criterion = "0.5"
diff = "0.1"
pretty_assertions = "1"
rand = "0.8"
wat = "1"
wasmparser = "0.206"
wasmprinter = "0.244"
wasmi = "0.31"

[features]
default = ["std"]
std = ["parity-wasm/std"]
sign_ext = ["parity-wasm/sign_ext"]
bulk = ["parity-wasm/bulk"]
simd = ["parity-wasm/simd"]

[lib]
bench = false
